---
- name: Transform the data DataClasses Attempt 1
  ansible.builtin.set_fact:
    plugin_filter_eth: "{{ data | eth_builder }}"
  vars:
    model: DCS-7050SX3-48YC8
    vars_file: "./vars/model_details/{{ model }}.yml"
    model_ethernet_interfaces: "{{ (lookup('ansible.builtin.file', vars_file) | from_yaml)['ethernet_interfaces']  }}"
    data:
      interfaces: "{{ model_ethernet_interfaces }}"
      rack_non_default_switchports: "{{ rack_non_default_switchports['switchports'] }}"
      inventory_hostname: "{{ inventory_hostname }}"


- name: Transform the data DataClasses Attempt 2
  ansible.builtin.set_fact:
    plugin_filter_eth2: "{{ data | eth_builder_2 }}"
  vars:
    model: DCS-7050SX3-48YC8
    vars_file: "./vars/model_details/{{ model }}.yml"
    model_ethernet_interfaces: "{{ (lookup('ansible.builtin.file', vars_file) | from_yaml)['ethernet_interfaces']  }}"
    data:
      interfaces: "{{ model_ethernet_interfaces }}"
      rack_non_default_switchports: "{{ rack_non_default_switchports['switchports'] }}"
      inventory_hostname: "{{ inventory_hostname }}"

- name: "Test Template Ethernet & Port-Channel Interfaces"
  ansible.builtin.template:
    src: "./templates/main.j2"
    dest: "./artifacts/{{ inventory_hostname }}/interfaces_jinja.yml"
    mode: 0750
  delegate_to: localhost
  changed_when: false

- name: Load Template Ethernet Interfaces
  ansible.builtin.include_vars:
    file: "./artifacts/{{ inventory_hostname }}/interfaces_jinja.yml"

- name: Debug Output
  block:
    - name: Test Output
      ansible.builtin.assert:
        that:
          - "ethernet_interfaces == plugin_filter_eth"

  rescue:
    - name: Diff Output
      ansible.utils.fact_diff:
        before: "{{ ethernet_interfaces | ansible.utils.to_paths }}"
        after: "{{ plugin_filter_eth2 | ansible.utils.to_paths }}"
