---
- name: Transform the data 2
  set_fact:
    plugin_filter_eth: "{{ data | eth_builder }}"
  vars:
    model: DCS-7050SX3-48YC8
    vars_file: "./vars/model_details/{{ model }}.yml"
    model_ethernet_interfaces: "{{ (lookup('ansible.builtin.file', vars_file) | from_yaml)['ethernet_interfaces']  }}"
    data:
      interfaces: "{{ model_ethernet_interfaces }}"
      rack_non_default_switchports: "{{ rack_non_default_switchports['switchports'] }}"
      inventory_hostname: "{{ inventory_hostname }}"

- name: "Test Template Ethernet & Port-Channel Interfaces"
  ansible.builtin.template:
    src: "./templates/main.j2"
    dest: "./artifacts/{{ inventory_hostname }}/interfaces_jinja.yml"
    mode: 0750
  delegate_to: localhost
  changed_when: false

- name: Load Template Ethernet Interfaces
  include_vars:
    file: "./artifacts/{{ inventory_hostname }}/interfaces_jinja.yml"

- name: Diff Output
  ansible.utils.fact_diff:
    before: "{{ plugin_filter_eth | ansible.utils.to_paths  }}"
    after: "{{ ethernet_interfaces | ansible.utils.to_paths  }}"
